= javaplsql

The *javaplsql* system supports calling Oracle PL/SQL procedures from Java via JDBC with
minimal preparatory work. Its main purpose is to make calling procdures with 
complex arguments (records, tables) simpler. There is no code generation, 
you just need to install three java collection types.

== API
There is one class +spinat.javaplsql.ProcedureCaller+. The constructor
----
 public ProcedureCaller(OracleConnection connection)
----
takes as argument the connection on which to execute the procedure calls.

The method +call+ on the class ProcedureCaller
----
public Map<String, Object> call(
           String name, int overload, Map<String, Object> args) throws SQLException
----
executes a stored procedure.	    
The parameter name is the name of the stored procedure, its format follows the usual
convention for oracle procedure names. It is possible use double quoted strings. 
Synonyms are also resolved. In fact the procedure +dbms_utility.name_resolve+ is 
used for resolving the procedure name.
The parameter overload is the number of the overload, numbering starts with 1.
The parameter args contains the arguments for the call, the arguments are mapped by name.
For each IN or IN OUT a value has to be given.
The return value contains a value for each OUT or in OUT parameter. 
If a function is called, its return value is placed under the key RETURN in the 
return value.
If there is no overloading, use the method
----
public Map<String, Object> call(
           String name, Map<String, Object> args) throws SQLException
----
The system needs three PL/SQL table types, their default definition is:
----
create type number_array as table of number;
create type varchar2_array as table of varchar2(32767);
create type date_array as table of date;
----
If you do not like the 
default names of the types you can change them. But you have to set the names
on the +ProcedureCaller+ object with the following methods:
----
public void setNumberTableName(String numberTableName) 
public void setVarchar2TableName(String varchar2TableName)
public void setDateTableName(String dateTableName)
----
== Type Map

.Java to PL/SQL
* arraylist -> table 
* Map<String,Object> -> record
* Number -> number
* String -> varchar2
* byte[] -> raw
* java.util.Date,java.sql.Date,java.sql.TimeStamp -> date
* Boolean, boolean -> boolean
* TreeMap<String,xyz> -> table of xyz_in_plsql index by varchar2(..);
* TreeMap<Integer,xyz> -> table of xyz_in_plsql index by binary_integer;


.PL/SQL to Java
* table -> ArrayList
* record -> Map<String,Object>
* number -> BigDecimal
* date -> java.sql.TimeStamp
* varchar2 -> String
* raw -> byte[]
* boolean -> Boolean
* sys_refcursor -> ArrayList of Map<String,Object>
* typed refcursor -> ArrayList of Map<String,Object>
* index by table -> TreeMap<String,?> or TreeMap<Integer,?>

Object types, clob, blob and timestamp are not supported. 
All records must have a named type, i.e. not defined as "%rowtype".

== Example
given a package:
----
create or replace package example1 as 
  type rec is record (x number,y varchar2(200),z date);
  type array is table of rec;
  procedure p(a in array,b out array);
end;
----
and a spec
----
create or replace package body example1 as
  procedure p(a in array,b out array) is
  begin
    b:=a;
  end;
end;
----
and connection being an OracleConnection, the following code
----
ProcedureCaller procCaller = new ProcedureCaller(connection);
// the input to he procedure example.p1 is a table of records
// the variable al is the table
ArrayList<Map<String, Object>> al = new ArrayList<>();
for (int i = 0; i < 10; i++) {
    // and the variable m is the record, in Java this is a Map<String,Object>
    Map<String, Object> m = new HashMap<>();
    m.put("X", i);
    m.put("Y", "text-" + i);
    m.put("Z", new Date()); // simple value?
    al.add(m);
}
// arguments are transferd by name
Map<String, Object> args = new HashMap<>();
// the argument names are case sensitive
args.put("A", al);
Map<String, Object> result = procCaller.call("example1.p", args);
// all out paramters are packed into a Map<String,Object> and returned
for (Object o : (ArrayList<Map<String, Object>>) result.get("B")) {
    System.out.println(o);
}
----
produces
----
{X=0, Y=text-0, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=1, Y=text-1, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=2, Y=text-2, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=3, Y=text-3, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=4, Y=text-4, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=5, Y=text-5, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=6, Y=text-6, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=7, Y=text-7, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=8, Y=text-8, Z=Sun Jul 05 11:38:14 CEST 2015}
{X=9, Y=text-9, Z=Sun Jul 05 11:38:14 CEST 2015}
----

== Installation
create these type definitions in the relevant schemas:
----
create type number_array as table of number;
create type varchar2_array as table of varchar2(32767);
create type date_array as table of date;
----
and copy the Java file ProcedureCaller into your project
(into what ever package you like).

== Things to do
* add support for raw
* add support for index by tables
* convert "java records" (class constining only of public fields) to oracle records
  the other way around?, type map for return records?
* try to separate conversion exeptions (our fault) from exceptions in the procedure
  wrap the actual procedure call with an eception handler
* handling of date-like typs, Timestamp, java.sql.Date. java.util.Date
* type checks in java, if string is too long for record field, the exception
should be thrown in Java.
